### ISSUE TITLE
The food trailer can not be loaded with different grades

### ISSUE THREAD

**Issue by Pumpuy71** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#79]
The food trailer can not be loaded with different grades,
I could not load wheat flour pallet and barley flour pallet onto the same trailer.

with the food trailer I could unload only one sort at the bakery, the other sort I was no longer accepted.

With the flat trailer everything went without problems with the unloader at the bakery

![01_01_wheat flour pallet and barley flour palette can not be loaded together in the trailer_1 2](https://user-images.githubusercontent.com/33676252/32815269-d03642b4-c9e5-11e7-8d07-9e07466d74f4.jpg)

![01_02_bild_load barley flour](https://user-images.githubusercontent.com/33676252/32815272-d8a18a9e-c9e5-11e7-96c3-6617a517de79.jpg)

![01_03_bild_wheat flour pallet unloaded then barley flour pallet is not going to unload_1 2](https://user-images.githubusercontent.com/33676252/32815294-e3538622-c9e5-11e7-9530-8eecc100aa96.jpg)

![01_04_bild_all right so is a trailer problem_1 2](https://user-images.githubusercontent.com/33676252/32815301-f2ae7fb4-c9e5-11e7-8600-5651f379c60e.jpg)

![01_05_bild_wheat flour pallet and barley flour pallet dumped together no problem](https://user-images.githubusercontent.com/33676252/32815310-00fb98c2-c9e6-11e7-9fd5-5602f124e149.jpg)

The 2 Bug is with the truck, behind the trailer hitch has no function. or is that just as a decoration.
That would be useful for maneuvering from the trailer.

![02_01_do not connect the trailer function_1 2](https://user-images.githubusercontent.com/33676252/32815348-341aed3e-c9e6-11e7-8eea-e9ea8663e853.jpg)

**Comment by BROADACRES16xFS17MAP** [comment]
TOLL trailers are only made for one product per trailer. This is because of the TOLL input triggers must only take one product at a time, similar to silo input. It takes one trailer then move onto the next. We can look at putting a trigger on the truck but not really a priority at this time. We usually use a tractor to maneuver the trailers. The pallets were mentioned on facebook yesterday. We are removing the pallets from TOLL building as per the issue I created in github this morning as you cant unload them. We now suggest to unload them using the flatbed in an area say the sawmill.
